// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1w-v7lPDGH7e-5tej80w4vksGiY_bejk',
    appId: '1:772302949662:web:2803311d40f45df97c8d0f',
    messagingSenderId: '772302949662',
    projectId: 'taxi-rider-eb595',
    authDomain: 'taxi-rider-eb595.firebaseapp.com',
    databaseURL: 'https://taxi-rider-eb595-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-rider-eb595.appspot.com',
    measurementId: 'G-W502P8LEPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVzHRpu-fHMIGB2qXloAJi2chRJpGqSJU',
    appId: '1:772302949662:android:316c382928c890f77c8d0f',
    messagingSenderId: '772302949662',
    projectId: 'taxi-rider-eb595',
    databaseURL: 'https://taxi-rider-eb595-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-rider-eb595.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdIHCpdZoiNGRryKm4e9lLmlbeUNVfs8c',
    appId: '1:772302949662:ios:b8bfea94185f7b6d7c8d0f',
    messagingSenderId: '772302949662',
    projectId: 'taxi-rider-eb595',
    databaseURL: 'https://taxi-rider-eb595-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-rider-eb595.appspot.com',
    iosClientId: '772302949662-bofs5gven2sb9ni0qjl21u32edbbu7qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxidriver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdIHCpdZoiNGRryKm4e9lLmlbeUNVfs8c',
    appId: '1:772302949662:ios:b8bfea94185f7b6d7c8d0f',
    messagingSenderId: '772302949662',
    projectId: 'taxi-rider-eb595',
    databaseURL: 'https://taxi-rider-eb595-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-rider-eb595.appspot.com',
    iosClientId: '772302949662-bofs5gven2sb9ni0qjl21u32edbbu7qb.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxidriver',
  );
}
